server:
  port: 8762
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true  #表示将自己注册进Eureka Server
    fetch-registry: true        #表示是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    serviceUrl:
      defaultZone: http://roker:roker@localhost:8761/eureka/




