server:
  port: 8099
spring:
  #???????
  application:
    name: rabbitmq-provider
  #??rabbitMq ???
  rabbitmq:
    host: 192.168.10.128
    port: 5672
    username: root
    password: root
    #??host ?????,??server??host
    virtual-host: roker