server:
  port: 8848
spring:
  application:
    name: monitor-demo

security:
  user:
    name: admin
    password: 1234
  basic:
    enabled: true
    # ?????????????????/admin??????
    path: /admin

# actuator???????
management:
  context-path: /admin
  # actuator?????????????api???????????
  port: 8888
  security:
    enabled: true
    roles: SUPERUSER
